Update workarea.cpp
synfig/synfig pull request #1761
Opened 2020-10-09 19:47 UTC by akshitagupta20

I rectified the error.

2020-10-10 05:44 UTC, ice0 commented
Please provide a link to the issue you are trying to fix.

2020-10-10 11:45 UTC, Keyikedalube requested changes

2020-10-10 11:45 UTC, Keyikedalube commented on synfig-studio/src/gui/workarea.cpp
> +    	}
You're supposed to fix indentation not remove `else`

2020-10-10 11:52 UTC, Keyikedalube commented
> I rectified the error.

@akshitagupta20 Edit your description and add this line

👉 Fixes #1760 👈

2020-10-13 01:43 UTC, ice0 commented
I am closing this PR because there is no response from @akshitagupta20.

2020-10-13 01:43 UTC, closed without merging