Add proper support for Arabic language to Text Layer
synfig/synfig pull request #2232
Opened 2021-07-18 06:33 UTC by rodolforg

Arabic, Hebrew and other languages that needs text shaping is now finally supported, thanks to FriBiDi and HarfBuzz libraries.
These libraries are already backend for Gtk/Glib, so there is not any change for packaging.

Fix #507, #1621

2021-07-18 06:35 UTC, rodolforg commented
Actually I don't know anything about those languages.
I tested only compared some random web texts appearance with that Synfig now provides.
So, please, test it – if you find any problem, and try to explain me what is wrong.

@Fahad-Alsaidi could you test it?

2021-07-18 06:54 UTC, rodolforg commented
Known issue: TAB is not rendered properly when HarfBuzz is enabled.

2021-07-18 19:53 UTC, rodolforg commented
Comparison: orange/yellow (whatever): Synfig Studio 1.4.0; the green one is current proposal
![Captura de tela de 2021-07-18 16-52-48](https://user-images.githubusercontent.com/1323987/126080425-3e6a0804-4dba-4a36-94e4-e701a2cefe0c.png)
![Captura de tela de 2021-07-18 16-51-42](https://user-images.githubusercontent.com/1323987/126080426-a8dfd74a-e2d2-43f8-ba29-52729284c684.png)

2021-07-19 04:05 UTC, ice0 requested changes

2021-07-19 05:05 UTC, rodolforg commented on synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
> +std::vector<std::string>
Do you mean to place `static` making it internal to `.cpp` or change the declaration in the `.h`?

2021-07-19 05:31 UTC, ice0 commented on synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
> +std::vector<std::string>
Change the declaration in the `.h`

2021-07-19 14:14 UTC, rodolforg commented on synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
> +std::vector<std::string>
Done

2021-07-19 14:14 UTC, rodolforg commented on synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
> +	FaceInfo(FT_Face ft_face)
Done

2021-07-19 14:18 UTC, rodolforg commented
The last forced push was to amend the following comments, due to @ice0 review:
-  Layer_FreeType: separate code for possible folders for fonts (make new method `static`)
-  Layer_FreeType: separate utf32 converter and line parser (remove the useless lambda function that I failed to implement in the next commit for FriBiDi) and solved the BiDi issue another way)
-  Layer_FreeType: add support to text shaping via HarfBuzz  (mark a construct as `explicit` and added some comments)

2021-07-21 00:11 UTC, rodolforg commented
@FirasH could you test it?
Mixing scripts, adding texts with multiple lines, etc.?

I don't know Arabic, Hebrew, etc... So I tried to make according to the manuals, but I had to adapt to Synfig needs.

2021-07-21 07:31 UTC, FirasH commented
> 
> 
> @FirasH could you test it?
> Mixing scripts, adding texts with multiple lines, etc.?
> 
> I don't know Arabic, Hebrew, etc... So I tried to make according to the manuals, but I had to adapt to Synfig needs.

Testing now!

2021-07-21 07:37 UTC, FirasH commented
I cannot start the AppVeyor image on Windows, need to build it.
I'll report ASAP.

2021-07-21 20:58 UTC, FirasH commented
1) Noticed that the word سلام is displayed with a spacing between the first and the second character as displayed here (top one is correct, made with Scribus):
![arabic-text-error-1](https://user-images.githubusercontent.com/6705690/126556475-a02f4947-636e-44aa-a36d-8ab449a76f4d.png)
even changing the first letter the issue is still present.
Keeping in mind Arabic is typed from right to left the problem is related to the part of text in the "middle" which is composed of two letters ل and ا

2) Noticed that the word كَلَام doesn't have the wrong spacing between first and second letter, but the "accents" are wrongly placed as displayed here (top one is correct):
![arabic-text-error-2](https://user-images.githubusercontent.com/6705690/126558895-b2e40e15-8e49-40b5-9581-0c28bc3785d0.png)
If I remove the "accents" characters are split as before:
![Screenshot_20210721_225708](https://user-images.githubusercontent.com/6705690/126559079-186f7cb2-44cd-4a44-ad4c-863df886bd51.png)

2021-07-22 00:15 UTC, rodolforg commented
Thank you, @FirasH !

I'll fix it. Luckily, this error happened after I tried to fix the case when I include an English word in an Arabic phrase like I show [a few comments above](https://github.com/synfig/synfig/pull/2232#issuecomment-882108781). I tested without that fix, and the text shapes like you showed me how it should do! :)

What about multiple lines? If a single phrase extends to next line it shapes differently if the second line would be another phrase starting with the same word? Er... So confusing. Let me show I want to say. Please consider each character-sequence as a valid word, and if a character-sequence repeats, it means they are the same word:

Case 1: one single phrase in two lines (5 words in the first line and the last 3 in the second line)
```
eeee dddd cccc bbbb aaaaa
hhhh gggg ffff.
```

Case 2: two phrases, one per line
```
.dddd cccc bbbb aaaaa
.mmmm jjjj ffff
```
My question is: does the `ffff` word could be shaped differently when comparing both cases above? It's the same word, but one is in the middle of the sentence, another (case 2) is at the sentence begining. 
Sorry for this question, but I don't know nothing about this language.

2021-07-23 08:39 UTC, FirasH commented
> What about multiple lines? If a single phrase extends to next line it shapes differently if the second line would be another phrase starting with the same word? Er... So confusing. Let me show I want to say. Please consider each character-sequence as a valid word, and if a character-sequence repeats, it means they are the same word:
> 
> Case 1: one single phrase in two lines (5 words in the first line and the last 3 in the second line)
> 
> ```
> eeee dddd cccc bbbb aaaaa
> .hhhh gggg ffff
> ```
> 
> Case 2: two phrases, one per line
> 
> ```
> .dddd cccc bbbb aaaaa
> .mmmm jjjj ffff
> ```
> 
> My question is: does the `ffff` word could be shaped differently when comparing both cases above? It's the same word using the same characters, but one is in the middle of the sentence, another (case 2) is at the sentence begining.
> Sorry for this question, but I don't know nothing about this language.
> 
> In English, Portuguese (my mother tongue/native language), French, Spanish, German, I know that "it doesn't matter": the first character needs to be changed to "upper case", but it's another character/byte that user need to type directly, it's not automatic. In Japanese, the position in phrase doesn't matter at all.
> 
> Explaining why I'm asking it: if it doesn't matter for Arabic and other languages, I can split the text into lines first and optimize the code a bit. Otherwise I could only do it at each frame rendering (in current text renderer).

In Arabic there is no upper cases, in your example `ffff` should loook the same for both Case 1 and Case 2.

2021-07-24 15:09 UTC, Fahad-Alsaidi commented
hi @rodolforg  
sorry for late reply... Actually I couldn't test the code, I didn't know how active freebidi & harfbuzz  while build synfig. This what I did:

> ./2-build-debug.sh all configure --with-fribidi --with-harfbuzz

2021-07-24 15:49 UTC, Fahad-Alsaidi commented
Great work I test it, and it works fine except Firas comments

2021-07-25 05:49 UTC, rodolforg commented
I believe I fixed it :)  @FirasH @Fahad-Alsaidi

2021-07-25 15:41 UTC, Fahad-Alsaidi commented
> I believe I fixed it :) @FirasH @Fahad-Alsaidi

well, there is no difference see 
![image](https://user-images.githubusercontent.com/1632566/126904506-93a1068d-35f1-45c0-9507-c7d04fd264b5.png)

I notice one bug in many fonts in my system, the last letter  is converted to rectangular see: 
in [Dubai font](https://www.ffonts.net/Dubai.font)
![image](https://user-images.githubusercontent.com/1632566/126904687-52d2f6b6-1371-4321-9323-6f17e8b814f0.png)
in [Amiri Quran font](https://arabicfonts.net/fonts/amiri-quran-regular) 
![image](https://user-images.githubusercontent.com/1632566/126904759-90b3b545-9234-4661-b737-9b4de837ae62.png)

here is a test file with fonts 
[arabic-test-file.zip](https://github.com/synfig/synfig/files/6874138/arabic-test-file.zip)

2021-07-25 15:49 UTC, rodolforg commented
Oh my. I was so happy before… :)
![Captura de tela de 2021-07-25 12-47-05](https://user-images.githubusercontent.com/1323987/126905108-89e6ff88-d419-4173-bf1d-b32fbccd66d5.png)
![Captura de tela de 2021-07-25 12-46-55](https://user-images.githubusercontent.com/1323987/126905111-6c29b4bd-416e-4ad8-b81d-5bb00831b199.png)
I'll try to understand what is happening.

2021-07-25 16:08 UTC, rodolforg commented
Hey! I think I found out the problem @Fahad-Alsaidi : synfig doesn't recognize the font file ;)
Try to write the filename (with file extension)! :D
![Captura de tela de 2021-07-25 13-08-28](https://user-images.githubusercontent.com/1323987/126905756-5f25b0b8-40b0-4f99-854b-71beeb6597e0.png)

2021-07-25 16:36 UTC, Fahad-Alsaidi commented
I test it again 
![image](https://user-images.githubusercontent.com/1632566/126905965-641763be-d9dd-4573-ab53-fed047684538.png)

I got this error:

> error: Layer_Freetype: Unable to open font face. (err=1): Dubai_Regular.otf

how can I check that I am using the same code you have??

2021-07-25 16:38 UTC, rodolforg commented
Are you building from source?
Test with git log and check the last commit ace87ebe9b751f53d2c93b33aff8d2c69e456e9e

2021-07-25 17:23 UTC, Fahad-Alsaidi commented
> Are you building from source?
 I started from beginning with deleting everything, then it works. All problems gone.
Thanks for great work.

2021-07-25 17:32 UTC, rodolforg commented
It was probably because I replaced some commits (`git push --force`) to create a clean Pull Request.
Sorry the inconvenience.
Thank you for your help.

2021-07-26 04:47 UTC, ice0 submitted a review, later dismissed

2021-07-26 12:58 UTC, yoSachinkr commented
Windows build doesn't work. It throughs following errors.
![Screenshot 2021-07-26 182544](https://user-images.githubusercontent.com/50204208/126992409-db84968f-397b-432d-b996-75f353c6dff4.png)
![Screenshot 2021-07-26 182532](https://user-images.githubusercontent.com/50204208/126992414-3604663c-36e0-47a9-9181-d4bfca00d2a4.png)
![Screenshot 2021-07-26 182516](https://user-images.githubusercontent.com/50204208/126992417-1d8269b9-dbfe-4f03-9d60-174f5f47977d.png)

2021-07-26 13:16 UTC, ice0 commented
> Windows build doesn't work. It throughs following errors.

I will take a look

2021-07-26 13:24 UTC, rodolforg commented
Commit 35733456a5744e0392a7dd556618760ad9753264 of 11/07  on master branch was fine.
Commit f32ae of 19/07 is not.

2021-07-26 14:35 UTC, rodolforg commented
@ice0 This is the error on Catalina (CMake+Ninja): `ld: library not found for -lharfbuzz`

2021-07-26 15:56 UTC, ice0 commented
> @ice0 This is the error on Catalina (CMake+Ninja): `ld: library not found for -lharfbuzz`
> 
> Strange… it's detected by CMake itself…

Yeah, CMake `XXX_LIBRARIES` doesn't include all required flags.


> Commit [3573345](https://github.com/synfig/synfig/commit/35733456a5744e0392a7dd556618760ad9753264) of 11/07 on master branch was fine.
> Commit f32ae of 19/07 is not.

It builds fine locally, so it looks like a temporary problem with MSYS packages on AppVeyor. 
Build script doesn't update packages before installing (just to save time), so I'll check tomorrow if that helps.

2021-07-26 17:33 UTC, rodolforg commented
> Yeah, CMake `XXX_LIBRARIES` doesn't include all required flags (I mean the paths of the libraries)
> https://cmake.org/cmake/help/latest/module/FindPkgConfig.html

So should it use `<XXX>_LINK_LIBRARIES` ? (I read it that page you linked)

2021-07-26 21:07 UTC, ice0 commented
> So should it use `<XXX>_LINK_LIBRARIES` ? (I read it that page you linked) or even `<XXX>_LDFLAGS`

I changed it to `<XXX>_LDFLAGS`. Please check PR (https://github.com/rodolforg/synfig/pull/3/)

2021-07-26 22:17 UTC, rodolforg commented
I made it a draft again in order to wait for the CI tests. If it runs OK, I'll rebase and push again.

2021-08-03 05:42 UTC, morevnaproject commented
Hi @rodolforg! Thank you so much for taking on this issue!

I have tested this PR and got some weird results.

I have entered a simple text into Google Translate and got the following:
![screenshot_001](https://user-images.githubusercontent.com/332868/127962911-3f3d9f5b-0d74-4108-95a7-7eecf09e98a3.png)
https://translate.google.ru/?sl=en&tl=ar&text=Synfig%20is%20an%20open-source%20animation%20software!&op=translate

Then I have copy-pasted the translated text to Synfig and got this result:
![screenshot_002](https://user-images.githubusercontent.com/332868/127963148-873c7a8a-36e2-4611-8bdc-11bd8c9e417f.png)

Somehow the words are in different order.

I am on Linux Mint 19, using Russian locale. Same result when I start Synfig with English (LANG=C) locale.

Attaching my sample file - 
[text-arabic-animatied-xy-slow.sifz.zip](https://github.com/synfig/synfig/files/6921305/text-arabic-animatied-xy-slow.sifz.zip)

@FirasH @Fahad-Alsaidi can you please test this file on your system and give screenshots how it looks? I am not familiar with Arabic language, maybe this is normal... ^__^"

2021-08-03 06:12 UTC, Fahad-Alsaidi commented
Hi @morevnaproject 
to get full RTL support, you will need to enforce RTL direction flag to the text.
See this screen shot from libreoffice when I set LTR flag:
![image](https://user-images.githubusercontent.com/1632566/127966389-4748fb41-c832-40d1-b1c8-3585dfa8d2f1.png)
here when set RTL flag
![image](https://user-images.githubusercontent.com/1632566/127966563-e467e0c2-e93f-41de-bd1e-2abd490cdd2a.png)

The simplest solution is to implement a radio button for setting RTL

2021-08-03 06:36 UTC, morevnaproject commented
@Fahad-Alsaidi I have noticed that in your examples all Arabic words are still remain in the same order, independently of RTL/LTR flag  (I have highlighted that part below) -

![screenshot_003](https://user-images.githubusercontent.com/332868/127968774-2ed60ad1-6a13-49df-8b77-9ed3ee6978aa.png)

The problem is that in my case Arabic words displayed in different order. Also, you can compare with the same text in Params panel (highlighted on screenshot below) - 
![screenshot_002](https://user-images.githubusercontent.com/332868/127969133-21c14134-3ff7-4de2-a680-d2ebeb0abaa3.png)

2021-08-03 06:51 UTC, rodolforg commented
> Somehow the words are in different order.
@morevnaproject 
It seems a font issue. Use an Arabic font :)

Anyway, it indeed has an error:
![Captura de tela de 2021-08-03 03-38-07](https://user-images.githubusercontent.com/1323987/127970524-bbd399ca-214b-4892-a5a0-81b57169e208.png)

GTK renders texts wrong here, as it supposes it's LTR. I don't know if we can fix it. But our text rendering is possible to fix by using @Fahad-Alsaidi suggestion: adding an extra layer parameter: LTR/RTL (an enum? or a boolean?)

2021-08-03 06:52 UTC, Fahad-Alsaidi commented
this mine 
![image](https://user-images.githubusercontent.com/1632566/127970946-7199758b-1189-4240-a244-0d9678407260.png)

2021-08-03 07:18 UTC, ice0 commented
> GTK renders texts wrong here, as it supposes it's LTR. I don't know if we can fix it. But our text rendering is possible to fix by using @Fahad-Alsaidi suggestion: adding an extra layer parameter: LTR/RTL (an enum? or a boolean?)

As discussed here (https://github.com/microsoft/vscode/issues/86667#issuecomment-631025893):

> I offer support for Unicode RTL character (200F) the editor. It ‏works in some programs like Telegram and GTK applications.

2021-08-03 11:47 UTC, rodolforg commented
@Fahad-Alsaidi Is the only problem "Synfig" word position, right? It should be at most-right position.

2021-08-03 12:01 UTC, rodolforg commented
> I offer support for Unicode RTL character (200F) the editor. It ‏works in some programs like Telegram and GTK applications.

It indeed works fine if someone type/paste this Unicode mark ("character")

2021-08-03 22:47 UTC, ice0 commented
> > I offer support for Unicode RTL character (200F) the editor. It ‏works in some programs like Telegram and GTK applications.
> 
> It indeed works fine if someone type/paste this Unicode mark ("character")

I was hoping that the OS will insert it itself if it understands that the text is written from right to left.  😅

2021-08-03 23:28 UTC, rodolforg commented
> I was hoping that the OS will insert it itself if it understands that the text is written from right to left. sweat_smile

I hoped it too. But I didn't think so: GTK+Pango seems to have a pretty good support for Arabic, but we can see it renders wrong the Konstantin's text in this comment: https://github.com/synfig/synfig/pull/2232#issuecomment-891546996 . Check Google Translator text versus Layer Panel versus Parameter Panel. The last two cases are pure GTK code and it renders in wrong order.

2021-08-04 23:28 UTC, khaledhosny commented
Paragraph direction can’t be automatically set, you can default to LTR or RTL based on the locale but 1) the setting must be stored in the file (otherwise opening the same file on a system with a different locale can give different results) 2) the user mut have a way to override it. You can pass paragraph direction to FriBiDi. I suggest either using [Raqm](https://github.com/HOST-Oman/libraqm) instead of wrapping HarfBuzz and FriBiDi yourself, or study its code for some pointers.

2021-08-04 23:30 UTC, khaledhosny commented
There is a heuristic that sets the paragraph direction based on the first character with a strong BiDi direction, but it fails in cases like this one. The RLM control character is one solution, but it is an invisible character and most users can‘t type it, so inserting it is rather inconvenient.

2021-08-05 03:28 UTC, rodolforg commented
So we can't escape from adding a new parameter: text direction LTR/RTL, right?

2021-08-05 10:41 UTC, khaledhosny commented
> So we can't escape from adding a new parameter: text direction LTR/RTL, right?

I think so.

2021-08-06 06:31 UTC, morevnaproject commented
> @morevnaproject
> It seems a font issue. Use an Arabic font :)

I tested it with "Noto Naksh Arabic" (was in my system) and also downloaded ["Amiri" font from Google Fonts](https://fonts.google.com/specimen/Amiri?subset=arabic) - same result... :-/
![screenshot_003](https://user-images.githubusercontent.com/332868/128466354-556809ff-5fa6-486a-8d86-90661a02e60a.png)



> Anyway, it indeed has an error:
> ![Captura de tela de 2021-08-03 03-38-07](https://user-images.githubusercontent.com/1323987/127970524-bbd399ca-214b-4892-a5a0-81b57169e208.png)

Is this screenshot made on Linux?

2021-08-06 08:00 UTC, rodolforg commented
> Is this screenshot made on Linux?

Yes. I almost never have access to a Windows machine.

2021-08-06 11:59 UTC, khaledhosny commented
Noto fonts are split into one script per font family, do Noto Naskh Arabic supports Arabic characters only, and it appears that synfig does not support font fallback. Fallback is very important for text layout since any given font will only support a subset of Unicode (it is not even technically possible for one font to support all currently defined Unicode characters, not with the existing font formats).

Since synfig already depends on GTK, has Pango been considered? It implements solutions for all of the issues discussed here and more.

2021-08-06 13:58 UTC, rodolforg commented
> I suggest either using [Raqm](https://github.com/HOST-Oman/libraqm) instead of wrapping HarfBuzz and FriBiDi yourself, or study its code for some pointers.


> Since synfig already depends on GTK, has Pango been considered? It implements solutions for all of the issues discussed here and more.

Synfig itself does not depend on GTK, but Synfig Studio (the GUI) does.

Somehow some day I found the `raqm` library. It does provide the text-shaping solution, but only as a bitmap text directly (as long as I saw the code): we have to pass the FreeFont font face with font/character size set. That is what makes text layer currently sooo slow. I already ported text layer to current synfig render engine, in a vector way and it's quite fast (as expected).

Pango has the same problem raqm, with another downside: I can't reproduce all current features of text layer.

I'll check how can I see it's an invalid glyph in order to (try to) use a fallback font face.

2021-08-06 14:00 UTC, rodolforg commented
> I tested it with "Noto Naksh Arabic" (was in my system) and also downloaded ["Amiri" font from Google Fonts](https://fonts.google.com/specimen/Amiri?subset=arabic) - same result... :-/
> 
> ![screenshot_003](https://user-images.githubusercontent.com/332868/128466354-556809ff-5fa6-486a-8d86-90661a02e60a.png)

@morevnaproject do you have FriBiDi and HarfBuzz installed?

2021-08-06 14:03 UTC, khaledhosny commented
Raqm does not do any rendering, it returns glyph IDs and positions. It needs size set on the FT_Face to be able to return glyph positions, but you can set it to the fonts UPEM if you don’t want it to do any scaling.

2021-08-07 19:08 UTC, rodolforg commented
Oh, thank you for correcting me. I looked an example code and it forced a size.
Anyway, for now I don't see any implementation difference between my code and raqm. As raqm isn't distributed in Debian, I'll try to keep away from this library for now.

I added the text direction parameter (Auto, LTR, RTL). I'll think now how to make the font fallback :/ I didn't want to add a new parameter nor make the "font family" a list :(

2021-08-08 02:32 UTC, morevnaproject commented
> @morevnaproject do you have FriBiDi and HarfBuzz installed?

Woops, I found that `fribidi-dev` is not installed.
We should add additional check to build system (I have used Autotools). ^__^

Rebuilding now...

2021-08-08 03:05 UTC, morevnaproject commented
@rodolforg I have made attempt to build latest commit with fribidi-dev installed (package version 0.19.7-2) and got the following error:
```
Making all in lyr_freetype
make[4]: Entering directory '/home/konstantin/sources/synfig/_production/synfig-core/src/modules/lyr_freetype'
  CXX      liblyr_freetype_la-lyr_freetype.lo
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp: In static member function 'static std::vector<std::vector<Layer_Freetype::TextSpan> > Layer_Freetype::fetch_text_lines(const string&, int)':
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:15: error: 'FriBidiBracketType' was not declared in this scope
   std::vector<FriBidiBracketType> bracket_types(line_size);
               ^~~~~~~~~~~~~~~~~~
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:15: note: suggested alternative: 'FriBidiParType'
   std::vector<FriBidiBracketType> bracket_types(line_size);
               ^~~~~~~~~~~~~~~~~~
               FriBidiParType
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:33: error: template argument 1 is invalid
   std::vector<FriBidiBracketType> bracket_types(line_size);
                                 ^
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:33: error: template argument 2 is invalid
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1368:102: error: request for member 'data' in 'bracket_types', which is of non-class type 'int'
 ribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
                                                                     ^~~~
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1368:33: error: 'fribidi_get_par_embedding_levels_ex' was not declared in this scope
   FriBidiLevel fribidi_result = fribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1368:33: note: suggested alternative: 'fribidi_get_par_embedding_levels'
   FriBidiLevel fribidi_result = fribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 fribidi_get_par_embedding_levels
Makefile:613: recipe for target 'liblyr_freetype_la-lyr_freetype.lo' failed
make[4]: *** [liblyr_freetype_la-lyr_freetype.lo] Error 1
make[4]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core/src/modules/lyr_freetype'
Makefile:568: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core/src/modules'
Makefile:471: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core/src'
Makefile:693: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core'
Makefile:561: recipe for target 'all' failed
make: *** [all] Error 2
```

2021-08-08 03:17 UTC, rodolforg commented
> > @morevnaproject do you have FriBiDi and HarfBuzz installed?
> 
> Woops, I found that `fribidi-dev` is not installed.
> We should add additional check to build system (I have used Autotools). ^__^

But it does have a check for FriBiDi o.O

2021-08-08 03:18 UTC, morevnaproject commented
> It isn't mandatory though.

I guess this is why it gave me different text rendering result. I think we should make it mandatory. ^__^

2021-08-14 19:27 UTC, rodolforg commented
> with fribidi-dev installed (package version 0.19.7-2)

Ouch. The API changed for 1.0.0 version.
https://github.com/fribidi/fribidi/releases?after=v1.0.1

I'll place a version detection

2021-08-23 03:48 UTC, morevnaproject commented
I think we should make fribidi  a required dependency - i.e. the configuration process should fail if no fribidi headers found.

Reason for that:
Synfig should give reproducible output from the same files.

Imagine one user creates animation with arabic text. He has a version of Synfig compiled with fribidi, so everything looks good for him.
Then he sends the animation file to another user (or maybe to cloud renderfarm? ^__^) and this second user has a version of Synfig without fribidi. So, he gets a different output and that can lead to confusions.

So I think we should make fribidi a required package to avoid such situations. ^__^

2021-08-30 03:45 UTC, rodolforg commented
>  Synfig should give reproducible output from the same files.

So we should require Harfbuzz too, right?

2021-08-30 15:59 UTC, morevnaproject commented
> So we should require Harfbuzz too, right?

Yes, Harfbuzz should be a mandatory requirement too. ^__^

2021-08-30 16:02 UTC, morevnaproject commented
> Yes, Harfbuzz should be a mandatory requirement too. ^__^

Note: Being said that, I am not sure which effect gives compiling without Harfbuss. I have made attempt to remove `hafbuzz-dev` package from my system , but that requested to remove many other useful packages. So I haven't did that. But I pretty much sure that compiling without Harfbuzz also makes RTL text look different. ^__^

2021-08-30 19:33 UTC, rodolforg commented
FriBiDi handles bidirectional text. 
HarfBuzz focus on text/character shaping. Not exactly on mixing text direction.

So, without harfbuzz is for those who doesn't need to handle Arabic, Hebrew, etc., i.e., as it is now.

2021-09-04 15:29 UTC, morevnaproject commented
> So, without harfbuzz is for those who doesn't need to handle Arabic, Hebrew, etc., i.e., as it is now.

I see. So, I still think Harfbuzz should be a mandatory requirement - to avoid different output id different conditions. We can't predict if user wants bi-directional/shaping text or not. ^__^

2021-09-04 22:40 UTC, rodolforg commented
@morevnaproject  Last commit I made harfbuzz required by default. If it is required, FriBiDi is automatically required too.

I still don't provide any support for fallback fonts :(

I don't have any idea about FriBiDi 0.18.x API so I can't implement it, and Ubuntu 16.04 building fails

2021-09-07 04:58 UTC, rodolforg commented
> @rodolforg I have made attempt to build latest commit with fribidi-dev installed (package version 0.19.7-2) and got the following error:
> 
> ```
> Making all in lyr_freetype
> make[4]: Entering directory '/home/konstantin/sources/synfig/_production/synfig-core/src/modules/lyr_freetype'
>   CXX      liblyr_freetype_la-lyr_freetype.lo
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp: In static member function 'static std::vector<std::vector<Layer_Freetype::TextSpan> > Layer_Freetype::fetch_text_lines(const string&, int)':
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:15: error: 'FriBidiBracketType' was not declared in this scope
>    std::vector<FriBidiBracketType> bracket_types(line_size);
>                ^~~~~~~~~~~~~~~~~~
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:15: note: suggested alternative: 'FriBidiParType'
>    std::vector<FriBidiBracketType> bracket_types(line_size);
>                ^~~~~~~~~~~~~~~~~~
>                FriBidiParType
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:33: error: template argument 1 is invalid
>    std::vector<FriBidiBracketType> bracket_types(line_size);
>                                  ^
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1367:33: error: template argument 2 is invalid
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1368:102: error: request for member 'data' in 'bracket_types', which is of non-class type 'int'
>  ribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
>                                                                      ^~~~
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1368:33: error: 'fribidi_get_par_embedding_levels_ex' was not declared in this scope
>    FriBidiLevel fribidi_result = fribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
>                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/konstantin/sources/synfig/synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp:1368:33: note: suggested alternative: 'fribidi_get_par_embedding_levels'
>    FriBidiLevel fribidi_result = fribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
>                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                  fribidi_get_par_embedding_levels
> Makefile:613: recipe for target 'liblyr_freetype_la-lyr_freetype.lo' failed
> make[4]: *** [liblyr_freetype_la-lyr_freetype.lo] Error 1
> make[4]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core/src/modules/lyr_freetype'
> Makefile:568: recipe for target 'all-recursive' failed
> make[3]: *** [all-recursive] Error 1
> make[3]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core/src/modules'
> Makefile:471: recipe for target 'all-recursive' failed
> make[2]: *** [all-recursive] Error 1
> make[2]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core/src'
> Makefile:693: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-core'
> Makefile:561: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

@morevnaproject I took a look at FriBiDi 0.19.7 source code.
You should replace
```c++
		std::vector<FriBidiBracketType> bracket_types(line_size);
		FriBidiLevel fribidi_result = fribidi_get_par_embedding_levels_ex(bidi_types.data(), bracket_types.data(), line_size,
															  &base_dir, bidi_levels.data());
```
with
```
		FriBidiLevel fribidi_result = fribidi_get_par_embedding_levels(bidi_types.data(), line_size,
															  &base_dir, bidi_levels.data());
```

2021-09-07 05:01 UTC, rodolforg commented
We could use remove the FriBiDi > 1.0.0 requirement and select code with `#if FRIBIDI_MAJOR_VERSION >= 1` and implement my proposed solution to your compilation problem with correspondent `#else`.

2021-09-10 08:38 UTC, morevnaproject commented
> We could remove the FriBiDi > 1.0.0 requirement and select code with `#if FRIBIDI_MAJOR_VERSION >= 1` and implement my proposed solution to your compilation problem with correspondent `#else`.

That would be great! I need to check the code you suggested first. Maybe there are other compilation issues...

2021-09-10 19:42 UTC, rodolforg commented
@ice0 could you please review https://github.com/synfig/synfig/pull/2232/commits/8e4375f4835e5d81c58cb330160d98cf1a2a7c20 ?

2021-09-10 19:51 UTC, rodolforg commented
> That would be great! I need to check the code you suggested first. Maybe there are other compilation issues...

@morevnaproject sorry I read the first phrase and then I pushed XD

2021-09-11 04:35 UTC, rodolforg commented
If the intention is to Animation document be reproducible I'm thinking about a new field: font fallback.
Otherwise each system could have its own fonts and the fallback could be different, rendering differently...
Argh.

2021-09-11 10:23 UTC, morevnaproject commented
@rodolforg Also, can you please add `fribidi-dev` package to this list? This package seems to be not present by default...
https://github.com/synfig/synfig/blob/2cbce018087fe63227afa099760ce83ecb4005f3/1-setup-linux-native.sh#L200-L232

2021-09-11 10:49 UTC, morevnaproject commented
> @morevnaproject sorry I read the first phrase and then I pushed XD

Wohooo! Now I have correct output for Arabic text!
![screenshot_006](https://user-images.githubusercontent.com/332868/132945272-004d1daa-1c44-4f79-8943-5532bee5ea15.png)
Thank you!

2021-09-11 10:53 UTC, morevnaproject commented
> If the intention is to Animation document be reproducible I'm thinking about a new field: font fallback.
> Otherwise each system could have its own fonts and the fallback could be different, rendering differently...
> Argh.

I think this is a responsibility of user to ship required fonts with his animation project.
In our practice, when sharing animation project we always put all font files into special subdirectory of the project. And in Synfig files we set relative paths to font files, so Synfig can easily find them when project is opened on any machine.

In fact the possibility to specify path to font files in Synfig is a great feature, which allows to solve problem of missing fonts in system.

So I think there is no need to bother with font replacement.

I think this PR is ready for merging! ^__^

2021-09-11 10:54 UTC, morevnaproject approved these changes

2021-09-11 19:03 UTC, rodolforg commented
> @rodolforg Also, can you please add `fribidi-dev` package to this list? This package seems to be not present by default...

Done. I didn't know if it was needed by ALT Linux and what would be the package name.

2021-09-12 15:38 UTC, morevnaproject commented
> I didn't know if it was needed by ALT Linux and what would be the package name.

For Alt Linux the package name seems to be `libfribidi-devel` - http://sisyphus.ru/en/srpm/Sisyphus/fribidi/repocop

2021-09-12 18:42 UTC, rodolforg commented
Trying to fix CMake build for MacOS I broke...

> > I didn't know if it was needed by ALT Linux and what would be the package name.
> 
> For Alt Linux the package name seems to be `libfribidi-devel` - http://sisyphus.ru/en/srpm/Sisyphus/fribidi/repocop

@morevnaproject done :)

2021-09-25 04:31 UTC, morevnaproject commented
@rodolforg Can you rebase, and resolve conflicts, please? ^__^

2021-09-25 04:33 UTC, rodolforg commented
> @rodolforg Can you rebase, and resolve conflicts, please? ^__^

I'll do it now! :)

2021-09-25 04:48 UTC, rodolforg commented
@morevnaproject  done

2021-09-25 15:30 UTC, morevnaproject approved these changes

2021-09-25 15:30 UTC, morevnaproject commented
@ice0 Can we merge this? ^__^

2021-10-02 15:00 UTC, ice0 commented
> @ice0 Can we merge this? ^__^

@morevnaproject Sure. 
@rodolforg Can you rebase please?

2021-10-02 15:39 UTC, rodolforg commented
@ice0 done

2021-10-03 04:29 UTC, ice0 approved these changes

2021-10-03 04:30 UTC, merged

2021-10-03 04:30 UTC, ice0 commented
Merged. Thank you!

2021-10-03 05:42 UTC, morevnaproject commented
Woohooo! :tada: :tada: :tada:

2021-10-03 14:25 UTC, morevnaproject commented
@rodolforg Now eagerly waiting a PR with optimized (cobra-enabled) text layer. ^__^

2021-10-03 16:49 UTC, Fahad-Alsaidi commented
I would like to thank @rodolforg & @morevnaproject & @ice0  for supporting RTL in synfig. You did a great job, thanks 🌹🌹

2021-10-03 22:52 UTC, rodolforg commented
> @rodolforg Now eagerly waiting a PR with optimized (cobra-enabled) text layer. ^__^

I'm working to make a clean version of what I wrote before HarfBuzz :) It still works, but I need to restore text alignment ("orientation" parameter).

@Fahad-Alsaidi 
Sadly we still don't provide a fallback-font for languages not supported by the chosen font.