Tab/Shift-Tab support
synfig/synfig pull request #2404
Opened 2021-11-06 06:00 UTC by veermetri05

Added support for Widget_Vector to respond to Tab and Shift-Tab as described in https://github.com/synfig/synfig/issues/1208

_This is my first pull request, let me know if I am doing something wrong._

2021-11-06 13:23 UTC, rodolforg requested changes
Thank you and congrats @veermetri05 :)
Please  address my comments here

2021-11-06 13:23 UTC, rodolforg commented on synfig-studio/src/gui/widgets/widget_vector.cpp
> +}
You are mixing indentation here.
Please use `Tab` only for alignment in this case.

2021-11-06 13:23 UTC, rodolforg commented on synfig-studio/src/gui/widgets/widget_vector.cpp
> +  }
Add `return true` right before finishing the `if` (same for the `if` below).

We don't want/need to call `Gtk::Box::on_key_press_event(key_event);` if we already handled the key event.

2021-11-06 13:23 UTC, rodolforg commented on synfig-studio/src/gui/widgets/widget_vector.cpp
> +  if((key_event->keyval == GDK_KEY_ISO_Left_Tab)) {
As it was not so obvious for us, what about add an inline comment after `{`: `// Shift+Tab`?

2021-11-06 15:54 UTC, veermetri05 commented
I have done the requested changes, is there anything else ?

2021-11-07 05:25 UTC, ice0 commented
@veermetri05 Looks good, awaiting @rodolforg review.

2021-11-07 13:27 UTC, rodolforg commented
@ice0 it's okay for me too.

Do you think he should change to `switch` instead of `if`?

Besides, we can squash and merge :)

2021-11-08 11:59 UTC, veermetri05 commented
@rodolforg Should I change to `switch` ? 

I don't think it would be good to use `switch` case, for now we are just checking `keyval`, **maybe** we need to use `state` sometimes then `switch` wouldn't be a good choice.

2021-11-08 23:50 UTC, rodolforg commented
> **maybe** we need to use `state` sometimes then `switch` wouldn't be a good choice.

You could check `state` inside (or not) the `switch`. But it isn't essential/critical for now.

2021-11-08 23:50 UTC, rodolforg approved these changes

2021-11-09 04:21 UTC, merged

2021-11-09 04:21 UTC, ice0 commented
Merged. Thank you!