Fixed crash when using Draw tool (Fedora/Flatpak)
synfig/synfig pull request #2445
Opened 2021-11-24 23:36 UTC by ice0

This issue is reproduced with Flatpak build and on Fedora.
The reason is that Fedora enables _GLIBCXX_ASSERTIONS  compile flag by default.
https://fedoraproject.org/wiki/Changes/HardeningFlags28

And Synfig crashes when reads off the end of the vector.

So I enabled this flag for CMake debug build too.
This will help us find such problems faster.

2021-11-24 23:42 UTC, rodolforg approved these changes

2021-11-25 02:36 UTC, rodolforg requested changes
Don't you think you should split into two commits or PR?

2021-11-25 07:17 UTC, ice0 commented
> Don't you think you should split into two commits or PR? 

Done.

> By the way, is `_GLIBCXX_ASSERTIONS` a GCC extension?

This is `libstc++` define, so it is not compiler dependent. 
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html

2021-11-25 20:00 UTC, rodolforg approved these changes

2021-11-26 01:52 UTC, merged