Make sure flags are correctly updated when setting renddesc
synfig/synfig pull request #2463
Opened 2021-12-17 21:45 UTC by FirasH

Fixes #2413

2021-12-24 17:56 UTC, rodolforg commented on synfig-studio/src/gui/renddesc.cpp
> +
Please do those esthetic changes in a separate commit. =)
And rebase this PR

2021-12-24 17:58 UTC, rodolforg requested changes
And please rebase this PR

2021-12-24 20:44 UTC, rodolforg approved these changes
You could let those changes here, but in other commit :)

Approved, anyway. It does fix the issue

2021-12-26 05:38 UTC, merged

2021-12-26 05:39 UTC, ice0 commented
Merged. Thank you!

2021-12-27 00:56 UTC, morevnaproject commented
Backported to 1.4.3 ^__^